/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

/*!40000 ALTER TABLE `mmrpg_threads` DISABLE KEYS */;
INSERT INTO `mmrpg_threads` (`thread_id`, `category_id`, `user_id`, `user_ip`, `thread_name`, `thread_token`, `thread_body`, `thread_frame`, `thread_colour`, `thread_date`, `thread_mod_date`, `thread_mod_user`, `thread_published`, `thread_locked`, `thread_sticky`, `thread_views`, `thread_votes`, `thread_target`) VALUES
    (1, 1, 2, '0.0.0.0', 'Example News & Updates Thread', 'example-news-updates-thread', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac commodo purus. Vivamus ultricies lorem in dignissim porta. Proin nibh metus, pellentesque eget consequat et, auctor nec augue. Mauris elementum felis bibendum, feugiat erat semper, tincidunt nisl. Proin at nunc ornare, dignissim diam ut, consequat sapien. Morbi fringilla eleifend efficitur. Nulla eget metus nec nulla pulvinar tincidunt. Integer eu gravida nulla, eget sodales purus. Integer fermentum mauris at pretium fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed venenatis felis vel lectus lobortis, at iaculis leo maximus. Nullam vitae eleifend risus.', '00', '', 1590803529, 0, 0, 1, 0, 0, 0, 0, 0),
    (2, 2, 2, '0.0.0.0', 'Example General Discussion Thread', 'example-general-discussion-thread', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac commodo purus. Vivamus ultricies lorem in dignissim porta. Proin nibh metus, pellentesque eget consequat et, auctor nec augue. Mauris elementum felis bibendum, feugiat erat semper, tincidunt nisl. Proin at nunc ornare, dignissim diam ut, consequat sapien. Morbi fringilla eleifend efficitur. Nulla eget metus nec nulla pulvinar tincidunt. Integer eu gravida nulla, eget sodales purus. Integer fermentum mauris at pretium fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed venenatis felis vel lectus lobortis, at iaculis leo maximus. Nullam vitae eleifend risus.', '01', '', 1590803529, 0, 0, 1, 0, 0, 0, 0, 0),
    (3, 3, 2, '0.0.0.0', 'Example Game Development Thread', 'example-game-development-thread', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac commodo purus. Vivamus ultricies lorem in dignissim porta. Proin nibh metus, pellentesque eget consequat et, auctor nec augue. Mauris elementum felis bibendum, feugiat erat semper, tincidunt nisl. Proin at nunc ornare, dignissim diam ut, consequat sapien. Morbi fringilla eleifend efficitur. Nulla eget metus nec nulla pulvinar tincidunt. Integer eu gravida nulla, eget sodales purus. Integer fermentum mauris at pretium fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed venenatis felis vel lectus lobortis, at iaculis leo maximus. Nullam vitae eleifend risus.', '02', '', 1590803529, 0, 0, 1, 0, 0, 0, 0, 0),
    (4, 4, 2, '0.0.0.0', 'Example Bug Reports Thread', 'example-bug-reports-thread', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac commodo purus. Vivamus ultricies lorem in dignissim porta. Proin nibh metus, pellentesque eget consequat et, auctor nec augue. Mauris elementum felis bibendum, feugiat erat semper, tincidunt nisl. Proin at nunc ornare, dignissim diam ut, consequat sapien. Morbi fringilla eleifend efficitur. Nulla eget metus nec nulla pulvinar tincidunt. Integer eu gravida nulla, eget sodales purus. Integer fermentum mauris at pretium fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed venenatis felis vel lectus lobortis, at iaculis leo maximus. Nullam vitae eleifend risus.', '03', '', 1590803529, 0, 0, 1, 0, 0, 0, 0, 0),
    (5, 5, 2, '0.0.0.0', 'Example Game Mechanics Thread', 'example-game-mechanics-thread', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac commodo purus. Vivamus ultricies lorem in dignissim porta. Proin nibh metus, pellentesque eget consequat et, auctor nec augue. Mauris elementum felis bibendum, feugiat erat semper, tincidunt nisl. Proin at nunc ornare, dignissim diam ut, consequat sapien. Morbi fringilla eleifend efficitur. Nulla eget metus nec nulla pulvinar tincidunt. Integer eu gravida nulla, eget sodales purus. Integer fermentum mauris at pretium fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed venenatis felis vel lectus lobortis, at iaculis leo maximus. Nullam vitae eleifend risus.', '00', '', 1590803529, 0, 0, 1, 0, 0, 0, 0, 0),
    (6, 7, 2, '0.0.0.0', 'Example Chat Room Thread', 'example-chat-room-thread', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac commodo purus. Vivamus ultricies lorem in dignissim porta. Proin nibh metus, pellentesque eget consequat et, auctor nec augue. Mauris elementum felis bibendum, feugiat erat semper, tincidunt nisl. Proin at nunc ornare, dignissim diam ut, consequat sapien. Morbi fringilla eleifend efficitur. Nulla eget metus nec nulla pulvinar tincidunt. Integer eu gravida nulla, eget sodales purus. Integer fermentum mauris at pretium fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed venenatis felis vel lectus lobortis, at iaculis leo maximus. Nullam vitae eleifend risus.', '01', '', 1590803529, 0, 0, 1, 0, 0, 0, 0, 0),
    (7, 8, 2, '0.0.0.0', 'Example Strategy Discussion Thread', 'example-strategy-discussion-thread', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac commodo purus. Vivamus ultricies lorem in dignissim porta. Proin nibh metus, pellentesque eget consequat et, auctor nec augue. Mauris elementum felis bibendum, feugiat erat semper, tincidunt nisl. Proin at nunc ornare, dignissim diam ut, consequat sapien. Morbi fringilla eleifend efficitur. Nulla eget metus nec nulla pulvinar tincidunt. Integer eu gravida nulla, eget sodales purus. Integer fermentum mauris at pretium fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed venenatis felis vel lectus lobortis, at iaculis leo maximus. Nullam vitae eleifend risus.', '02', '', 1590803529, 0, 0, 1, 0, 0, 0, 0, 0),
    (8, 9, 2, '0.0.0.0', 'Example Roleplay & Games Thread', 'example-roleplay-games-thread', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac commodo purus. Vivamus ultricies lorem in dignissim porta. Proin nibh metus, pellentesque eget consequat et, auctor nec augue. Mauris elementum felis bibendum, feugiat erat semper, tincidunt nisl. Proin at nunc ornare, dignissim diam ut, consequat sapien. Morbi fringilla eleifend efficitur. Nulla eget metus nec nulla pulvinar tincidunt. Integer eu gravida nulla, eget sodales purus. Integer fermentum mauris at pretium fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed venenatis felis vel lectus lobortis, at iaculis leo maximus. Nullam vitae eleifend risus.', '03', '', 1590803529, 0, 0, 1, 0, 0, 0, 0, 0),
    (9, 10, 2, '0.0.0.0', 'Example Fanart & Fanfics Thread', 'example-fanart-fanfics-thread', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac commodo purus. Vivamus ultricies lorem in dignissim porta. Proin nibh metus, pellentesque eget consequat et, auctor nec augue. Mauris elementum felis bibendum, feugiat erat semper, tincidunt nisl. Proin at nunc ornare, dignissim diam ut, consequat sapien. Morbi fringilla eleifend efficitur. Nulla eget metus nec nulla pulvinar tincidunt. Integer eu gravida nulla, eget sodales purus. Integer fermentum mauris at pretium fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed venenatis felis vel lectus lobortis, at iaculis leo maximus. Nullam vitae eleifend risus.', '04', '', 1590803529, 0, 0, 1, 0, 0, 0, 0, 0)
    ;
/*!40000 ALTER TABLE `mmrpg_threads` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
