/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

/*!40000 ALTER TABLE `mmrpg_saves` DISABLE KEYS */;
INSERT INTO `mmrpg_saves` (`save_id`, `user_id`, `save_counters`, `save_values`, `save_values_battle_index`, `save_values_battle_complete`, `save_values_battle_failure`, `save_values_battle_rewards`, `save_values_battle_settings`, `save_values_battle_items`, `save_values_battle_abilities`, `save_values_battle_stars`, `save_values_robot_database`, `save_values_robot_alts`, `save_values_battle_hearts`, `save_flags`, `save_settings`, `save_cache_date`, `save_file_name`, `save_file_path`, `save_date_created`, `save_date_accessed`, `save_date_modified`, `save_patches_applied`) VALUES
    (1, 1, '{"battle_points":0}', '{"battle_index":[],"last_load":1590803529,"last_save":1590803529}', '', '[]', '[]', '{"dr-light":{"player_token":"dr-light","player_points":0,"player_abilities":{"buster-shot":{"ability_token":"buster-shot"},"light-buster":{"ability_token":"light-buster"}},"player_robots":{"mega-man":{"flags":[],"values":[],"counters":[],"robot_token":"mega-man","robot_level":1,"robot_experience":999,"robot_energy":0,"robot_attack":0,"robot_defense":0,"robot_speed":0,"robot_energy_pending":0,"robot_attack_pending":0,"robot_defense_pending":0,"robot_speed_pending":0,"robot_abilities":{"buster-shot":{"ability_token":"buster-shot"}}}}}}', '{"dr-light":{"player_token":"dr-light","player_robots":{"mega-man":{"flags":[],"values":[],"counters":[],"robot_token":"mega-man","robot_abilities":{"buster-shot":{"ability_token":"buster-shot"}},"original_player":"dr-light"}}}}', '[]', '["buster-shot","light-buster"]', '[]', '{"mega-man":{"robot_token":"mega-man","robot_unlocked":1,"robot_summoned":0,"robot_encountered":0,"robot_scanned":0}}', '[]', '', '{"events":{"unlocked-ability_buster-shot":true,"unlocked-ability_light-buster":true,"unlocked-player_dr-light":true,"unlocked-robot_mega-man":true,"unlocked-robot_dr-light_mega-man":true}}', '{"this_player_token":"dr-light"}', '20200526-2022', '', '', 1590803529, 1590803529, 1590803529, ''),
    (2, 2, '{"battle_points":0}', '{"battle_index":[],"last_load":1590803362,"last_save":1590803362}', '', '[]', '[]', '{"dr-light":{"player_token":"dr-light","player_points":0,"player_abilities":{"buster-shot":{"ability_token":"buster-shot"},"light-buster":{"ability_token":"light-buster"}},"player_robots":{"mega-man":{"flags":[],"values":[],"counters":[],"robot_token":"mega-man","robot_level":1,"robot_experience":999,"robot_energy":0,"robot_attack":0,"robot_defense":0,"robot_speed":0,"robot_energy_pending":0,"robot_attack_pending":0,"robot_defense_pending":0,"robot_speed_pending":0,"robot_abilities":{"buster-shot":{"ability_token":"buster-shot"}}}}}}', '{"dr-light":{"player_token":"dr-light","player_robots":{"mega-man":{"flags":[],"values":[],"counters":[],"robot_token":"mega-man","robot_abilities":{"buster-shot":{"ability_token":"buster-shot"}},"original_player":"dr-light"}}}}', '[]', '["buster-shot","light-buster"]', '[]', '{"mega-man":{"robot_token":"mega-man","robot_unlocked":1,"robot_summoned":0,"robot_encountered":0,"robot_scanned":0}}', '[]', '', '{"events":{"unlocked-ability_buster-shot":true,"unlocked-ability_light-buster":true,"unlocked-player_dr-light":true,"unlocked-robot_mega-man":true,"unlocked-robot_dr-light_mega-man":true}}', '{"this_player_token":"dr-light"}', '20200526-2022', '', '', 1590803362, 1590803362, 1590803362, ''),
    (3, 3, '{"battle_points":0}', '{"battle_index":[],"last_load":1590803743,"last_save":1590803744}', '', '[]', '[]', '{"dr-light":{"player_token":"dr-light","player_points":0,"player_abilities":{"buster-shot":{"ability_token":"buster-shot"},"light-buster":{"ability_token":"light-buster"}},"player_robots":{"mega-man":{"flags":[],"values":[],"counters":[],"robot_token":"mega-man","robot_level":1,"robot_experience":999,"robot_energy":0,"robot_attack":0,"robot_defense":0,"robot_speed":0,"robot_energy_pending":0,"robot_attack_pending":0,"robot_defense_pending":0,"robot_speed_pending":0,"robot_abilities":{"buster-shot":{"ability_token":"buster-shot"}}}}}}', '{"dr-light":{"player_token":"dr-light","player_robots":{"mega-man":{"flags":[],"values":[],"counters":[],"robot_token":"mega-man","robot_abilities":{"buster-shot":{"ability_token":"buster-shot"}},"original_player":"dr-light"}}}}', '[]', '["buster-shot","light-buster"]', '[]', '{"mega-man":{"robot_token":"mega-man","robot_unlocked":1,"robot_summoned":0,"robot_encountered":0,"robot_scanned":0}}', '[]', '', '{"events":{"unlocked-ability_buster-shot":true,"unlocked-ability_light-buster":true,"unlocked-player_dr-light":true,"unlocked-robot_mega-man":true,"unlocked-robot_dr-light_mega-man":true}}', '{"this_player_token":"dr-light"}', '20200526-2022', '', '', 1590803744, 1590803744, 1590803744, ''),
    (4, 4, '{"battle_points":0}', '{"battle_index":[],"last_load":1590803661,"last_save":1590803661}', '', '[]', '[]', '{"dr-light":{"player_token":"dr-light","player_points":0,"player_abilities":{"buster-shot":{"ability_token":"buster-shot"},"light-buster":{"ability_token":"light-buster"}},"player_robots":{"mega-man":{"flags":[],"values":[],"counters":[],"robot_token":"mega-man","robot_level":1,"robot_experience":999,"robot_energy":0,"robot_attack":0,"robot_defense":0,"robot_speed":0,"robot_energy_pending":0,"robot_attack_pending":0,"robot_defense_pending":0,"robot_speed_pending":0,"robot_abilities":{"buster-shot":{"ability_token":"buster-shot"}}}}}}', '{"dr-light":{"player_token":"dr-light","player_robots":{"mega-man":{"flags":[],"values":[],"counters":[],"robot_token":"mega-man","robot_abilities":{"buster-shot":{"ability_token":"buster-shot"}},"original_player":"dr-light"}}}}', '[]', '["buster-shot","light-buster"]', '[]', '{"mega-man":{"robot_token":"mega-man","robot_unlocked":1,"robot_summoned":0,"robot_encountered":0,"robot_scanned":0}}', '[]', '', '{"events":{"unlocked-ability_buster-shot":true,"unlocked-ability_light-buster":true,"unlocked-player_dr-light":true,"unlocked-robot_mega-man":true,"unlocked-robot_dr-light_mega-man":true}}', '{"this_player_token":"dr-light"}', '20200526-2022', '', '', 1590803661, 1590803661, 1590803661, ''),
    (5, 5, '{"battle_points":0}', '{"battle_index":[],"last_load":1590803398,"last_save":1590803398}', '', '[]', '[]', '{"dr-light":{"player_token":"dr-light","player_points":0,"player_abilities":{"buster-shot":{"ability_token":"buster-shot"},"light-buster":{"ability_token":"light-buster"}},"player_robots":{"mega-man":{"flags":[],"values":[],"counters":[],"robot_token":"mega-man","robot_level":1,"robot_experience":999,"robot_energy":0,"robot_attack":0,"robot_defense":0,"robot_speed":0,"robot_energy_pending":0,"robot_attack_pending":0,"robot_defense_pending":0,"robot_speed_pending":0,"robot_abilities":{"buster-shot":{"ability_token":"buster-shot"}}}}}}', '{"dr-light":{"player_token":"dr-light","player_robots":{"mega-man":{"flags":[],"values":[],"counters":[],"robot_token":"mega-man","robot_abilities":{"buster-shot":{"ability_token":"buster-shot"}},"original_player":"dr-light"}}}}', '[]', '["buster-shot","light-buster"]', '[]', '{"mega-man":{"robot_token":"mega-man","robot_unlocked":1,"robot_summoned":0,"robot_encountered":0,"robot_scanned":0}}', '[]', '', '{"events":{"unlocked-ability_buster-shot":true,"unlocked-ability_light-buster":true,"unlocked-player_dr-light":true,"unlocked-robot_mega-man":true,"unlocked-robot_dr-light_mega-man":true}}', '{"this_player_token":"dr-light"}', '20200526-2022', '', '', 1590803398, 1590803398, 1590803398, '')
    ;
/*!40000 ALTER TABLE `mmrpg_saves` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
