/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `mmrpg_index_items` (
  `item_id` mediumint(8) NOT NULL AUTO_INCREMENT COMMENT 'Item ID',
  `item_token` varchar(100) NOT NULL COMMENT 'Item Token',
  `item_name` varchar(100) NOT NULL COMMENT 'Item Name',
  `item_game` varchar(10) NOT NULL COMMENT 'Item Game',
  `item_group` varchar(32) NOT NULL COMMENT 'Item Group',
  `item_class` varchar(32) NOT NULL COMMENT 'Item Class',
  `item_subclass` varchar(32) NOT NULL COMMENT 'Item Subclass',
  `item_master` varchar(100) NOT NULL COMMENT 'Item Master',
  `item_number` varchar(10) NOT NULL COMMENT 'Item Number',
  `item_image` varchar(64) NOT NULL COMMENT 'Item Image',
  `item_image_sheets` smallint(3) NOT NULL DEFAULT '1' COMMENT 'Item Image Sheets',
  `item_image_size` smallint(3) NOT NULL DEFAULT '40' COMMENT 'Item Image Size',
  `item_image_editor` mediumint(8) NOT NULL DEFAULT '0' COMMENT 'Item Image Editor',
  `item_type` varchar(32) NOT NULL COMMENT 'Item Type',
  `item_type2` varchar(32) NOT NULL COMMENT 'Item ENGINE 2',
  `item_description` text NOT NULL COMMENT 'Item Description',
  `item_description2` text NOT NULL COMMENT 'Item Description 2',
  `item_description_use` text NOT NULL COMMENT 'Item Description (Use)',
  `item_description_hold` text NOT NULL COMMENT 'Item Description (Hold)',
  `item_description_shop` text NOT NULL COMMENT 'Item Description (Shop)',
  `item_speed` smallint(6) NOT NULL DEFAULT '1' COMMENT 'Item Speed',
  `item_energy` smallint(6) NOT NULL DEFAULT '1' COMMENT 'Item Energy',
  `item_energy_percent` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Item Energy Percent',
  `item_damage` smallint(6) NOT NULL DEFAULT '0' COMMENT 'Item Damage',
  `item_damage_percent` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Item Damage Percent',
  `item_damage2` smallint(6) NOT NULL DEFAULT '0' COMMENT 'Item Damage 2',
  `item_damage2_percent` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Item Damage 2 Percent',
  `item_recovery` smallint(6) NOT NULL DEFAULT '0' COMMENT 'Item Recovery',
  `item_recovery_percent` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Item Recovery Percent',
  `item_recovery2` smallint(6) NOT NULL DEFAULT '0' COMMENT 'Item Recovery 2',
  `item_recovery2_percent` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Item Recovery 2 Percent',
  `item_accuracy` smallint(3) NOT NULL DEFAULT '0' COMMENT 'Item Accuracy',
  `item_price` mediumint(8) NOT NULL DEFAULT '0' COMMENT 'Item Price',
  `item_value` mediumint(8) NOT NULL DEFAULT '0' COMMENT 'Item Value',
  `item_target` varchar(64) NOT NULL COMMENT 'Item Target',
  `item_frame` varchar(32) NOT NULL COMMENT 'Item Frame',
  `item_frame_animate` varchar(256) NOT NULL COMMENT 'Item Frame Animate',
  `item_frame_index` varchar(256) NOT NULL COMMENT 'Item Frame Index',
  `item_frame_offset` varchar(100) NOT NULL COMMENT 'Item Frame Offset',
  `item_frame_styles` varchar(100) NOT NULL COMMENT 'Item Frame Styles',
  `item_frame_classes` varchar(100) NOT NULL COMMENT 'Item Frame Classes',
  `attachment_frame` varchar(32) NOT NULL COMMENT 'Attachment Frame',
  `attachment_frame_animate` varchar(256) NOT NULL COMMENT 'Attachment Frame Animate',
  `attachment_frame_index` varchar(256) NOT NULL COMMENT 'Attachment Frame Index',
  `attachment_frame_offset` varchar(100) NOT NULL COMMENT 'Attachment Frame Offset',
  `attachment_frame_styles` varchar(100) NOT NULL COMMENT 'Attachment Frame Styles',
  `attachment_frame_classes` varchar(100) NOT NULL COMMENT 'Attachment Frame Classes',
  `item_functions` varchar(128) NOT NULL COMMENT 'Item Functions',
  `item_flag_hidden` smallint(1) NOT NULL DEFAULT '0' COMMENT 'Item Flag Hidden',
  `item_flag_complete` smallint(1) NOT NULL DEFAULT '0' COMMENT 'Item Flag Complete',
  `item_flag_published` smallint(1) NOT NULL DEFAULT '1' COMMENT 'Item Flag Published',
  `item_order` smallint(8) NOT NULL DEFAULT '0' COMMENT 'Item Order',
  PRIMARY KEY (`item_id`),
  KEY `item_token` (`item_token`),
  KEY `item_class` (`item_class`),
  KEY `item_subclass` (`item_subclass`),
  KEY `item_type` (`item_type`),
  KEY `item_type2` (`item_type2`),
  KEY `item_flag_hidden` (`item_flag_hidden`),
  KEY `item_flag_complete` (`item_flag_complete`),
  KEY `item_flag_published` (`item_flag_published`),
  KEY `item_flag_hidden_complete_published` (`item_flag_hidden`,`item_flag_complete`,`item_flag_published`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
