/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `mmrpg_roles` (
  `role_id` mediumint(8) NOT NULL AUTO_INCREMENT COMMENT 'Role ID',
  `role_name` varchar(100) NOT NULL COMMENT 'Role Name',
  `role_name_full` varchar(100) NOT NULL COMMENT 'Role Name (Full)',
  `role_token` varchar(100) NOT NULL COMMENT 'Role Token',
  `role_level` mediumint(8) NOT NULL COMMENT 'Role Level',
  `role_icon` varchar(32) DEFAULT NULL COMMENT 'Role Icon',
  `role_colour` varchar(32) DEFAULT NULL COMMENT 'Role Colour',
  PRIMARY KEY (`role_id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
